name: DPP-Core
version: 5.4.4
description: All DP-PLUGINS plugins require this plugin.
main: com.darksoldier1404.dppc.DPPCore
authors: [ DEAD_POOLIO_ ]
api-version: 1.20
libraries:
  - com.zaxxer:HikariCP:5.1.0
  - org.mariadb.jdbc:mariadb-java-client:3.4.1
  - org.xerial:sqlite-jdbc:3.46.1.3
  - redis.clients:jedis:5.2.0
loadbefore:
  - PlaceholderAPI
softdepend:
  - Essentials
  - PlaceholderAPI
  - ProtocolLib
  - LuckPerms
  - WorldGuard
  - Vault
commands:
  dppc:
  dppca:
  dppcp:
  dppcdi: